export const countries = [
  {
    value: "US",
    label: "United States",
    phoneCode: "+1",
    currencyCode: "USD",
    countryCode: "US",
    flag: "🇺🇸",
  },
  {
    value: "UK",
    label: "United Kingdom",
    phoneCode: "+44",
    currencyCode: "GBP",
    countryCode: "GB",
    flag: "🇬🇧",
  },
  {
    value: "IN",
    label: "India",
    phoneCode: "+91",
    currencyCode: "INR",
    countryCode: "IN",
    flag: "🇮🇳",
  },
  {
    value: "CA",
    label: "Canada",
    phoneCode: "+1",
    currencyCode: "CAD",
    countryCode: "CA",
    flag: "🇨🇦",
  },
  {
    value: "AU",
    label: "Australia",
    phoneCode: "+61",
    currencyCode: "AUD",
    countryCode: "AU",
    flag: "🇦🇺",
  },
  {
    value: "DE",
    label: "Germany",
    phoneCode: "+49",
    currencyCode: "EUR",
    countryCode: "DE",
    flag: "🇩🇪",
  },
  {
    value: "FR",
    label: "France",
    phoneCode: "+33",
    currencyCode: "EUR",
    countryCode: "FR",
    flag: "🇫🇷",
  },
  {
    value: "JP",
    label: "Japan",
    phoneCode: "+81",
    currencyCode: "JPY",
    countryCode: "JP",
    flag: "🇯🇵",
  },
  {
    value: "BR",
    label: "Brazil",
    phoneCode: "+55",
    currencyCode: "BRL",
    countryCode: "BR",
    flag: "🇧🇷",
  },
  {
    value: "MX",
    label: "Mexico",
    phoneCode: "+52",
    currencyCode: "MXN",
    countryCode: "MX",
    flag: "🇲🇽",
  },
  {
    value: "ES",
    label: "Spain",
    phoneCode: "+34",
    currencyCode: "EUR",
    countryCode: "ES",
    flag: "🇪🇸",
  },
  {
    value: "IT",
    label: "Italy",
    phoneCode: "+39",
    currencyCode: "EUR",
    countryCode: "IT",
    flag: "🇮🇹",
  },
  {
    value: "NL",
    label: "Netherlands",
    phoneCode: "+31",
    currencyCode: "EUR",
    countryCode: "NL",
    flag: "🇳🇱",
  },
  {
    value: "SE",
    label: "Sweden",
    phoneCode: "+46",
    currencyCode: "SEK",
    countryCode: "SE",
    flag: "🇸🇪",
  },
  {
    value: "SG",
    label: "Singapore",
    phoneCode: "+65",
    currencyCode: "SGD",
    countryCode: "SG",
    flag: "🇸🇬",
  },
];
